/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LawyersRouteImport } from './routes/lawyers'
import { Route as ProBonoRouteImport } from './routes/pro-bono'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyersRoute = LawyersRouteImport.update({
  id: '/lawyers',
  path: '/lawyers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProBonoRoute = ProBonoRouteImport.update({
  id: '/pro-bono',
  path: '/pro-bono',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/lawyers': typeof LawyersRoute
  '/pro-bono': typeof ProBonoRoute
  '/triage': typeof TriageRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/lawyers': typeof LawyersRoute
  '/pro-bono': typeof ProBonoRoute
  '/triage': typeof TriageRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/lawyers': typeof LawyersRoute
  '/pro-bono': typeof ProBonoRoute
  '/triage': typeof TriageRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/lawyers'
    | '/pro-bono'
    | '/triage'
    | '/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/lawyers'
    | '/pro-bono'
    | '/triage'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/lawyers'
    | '/pro-bono'
    | '/triage'
    | '/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LawyersRoute: typeof LawyersRoute
  ProBonoRoute: typeof ProBonoRoute
  TriageRoute: typeof TriageRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyers': {
      id: '/lawyers'
      path: '/lawyers'
      fullPath: '/lawyers'
      preLoaderRoute: typeof LawyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-bono': {
      id: '/pro-bono'
      path: '/pro-bono'
      fullPath: '/pro-bono'
      preLoaderRoute: typeof ProBonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LawyersRoute: LawyersRoute,
  ProBonoRoute: ProBonoRoute,
  TriageRoute: TriageRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
